
__help__ = """


- /boobs: the balloons that boys like!! 
 - /neko: neko neko ni!! cats like me!! 
 - /feet: Peeps like to see feets too...
 - /yuri: Now its a familiar thing.... girls kissing and teasing each other.... 
 - /trap: "Im a boy from the inside" 
 - /futanari: "im a girl who's a boy and likes to fuk girls" 
 - /hololewd: Holo Lewds...?.. 
 - /lewdkemo: Kemo Lewds.....?... 
 - /sologif: Girls ruining themselves up..... 
 - /cumgif: Milk flowing out like a waterfall..... 
 - /erokemo: Ero-Kemo Images...?...
 - /lesbian: The englis term for "yuri"... you know what i mean hehe.... 
 - /wallpaper: Wallpapers....?....
 - /lewdk: Kitsune Lewds....?..... 
 - /ngif: Meow meow cat girls!! 
 - /tickle: "Do i have a ticklish side?" 
 - /lewd: Lewds!!! 
 - /feed: Say Ahhhhhh!!!! 
 - /eroyuri: Ero-Yuri source Images....?....
 - /eron: Ero-Neko source Images...?....
 - /cumpic: Milk but not in action...!! 
 - /bj: Eating the hot rod!! action!! 
 - /blowjob: Eating The hot rod!! Still pics?! 
 - /nekonsfwgif: Catgirls but not safe!! 
 - /solo: Girls ruining them but pics!! 
 - /kemonomimi: KemonoMimi source Images....?....
 - /gasm: Sends Orgasm pics!! 
 - /poke: "My finger at ur body hitting hard!!!" 
 - /anal: "But i poop from there!!"
 - /hentai: obviously u know..... images
 - /erofeet: feets but ero.... 
 - /holo: Holo...?... 
 - /tits: jiggly juggly tities!!! 
 - /pussy: My fav!! ah u know now..... 
 - /holoero: Ero-Holo...?... there are too many combinations.... 
 - /pussypic: Pics of pushies...... 
 - /randomgif: Take out tht thingy...!! 
 - /classic: Classical..?... 
 - /kuni: Pussy Lick!! Yum!! 
 - /waifu: Waifu?....!??... 
 - /kiss: Lips..locked... dripping..juice... 
 - /femdom: Femdom?...!?... 
 - /hug: "Am i your favorite!??!" 
 - /erok: Combos.... Ero-kitsune?!.. 
 - /foxgirl: Foxes are clever...so are girls... are you getting what i am saying?!..
 - /ero: Ero!!.... 
 - /smug: Smug...?...
 - /baka: "Omae wa baka desu!!" 
 - /slap: red cheeks... 
 - /spank: red.... 
 """
__mod_name__ = "LEWDS"

